--- #YAML:1.0
name:               Sereal-Encoder
version:            2.06
abstract:           Fast, compact, powerful binary serialization
author:
    - Steffen Mueller <smueller@cpan.org>, Yves Orton <yves@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Data::Dumper:       0
    ExtUtils::ParseXS:  2.21
    File::Find:         0
    File::Path:         0
    File::Spec:         0
    Scalar::Util:       0
    Sereal::Decoder:    2.06
    Test::LongString:   0
    Test::More:         0.88
    Test::Warn:         0
requires:
    perl:      5.008
    XSLoader:  0
resources:
    bugtracker:  https://github.com/Sereal/Sereal/issues
    repository:  git://github.com/Sereal/Sereal.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
